<a href="https://colab.research.google.com/github/princeowaowa/python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Code to create a sample CSV file in Colab's current workspace
import pandas as pd

# Sample data
data = {
    'Name': [' Alice ', 'Bob', 'Alice', 'Charlie', None],
    'Age': [25, 30, 25, None, 22],
    'Salary': ['50000', '60000', '50000', '70000', '45000']
}

# Create a DataFrame and save it as 'your_file.csv'
sample_df = pd.DataFrame(data)
sample_df.to_csv('your_file.csv', index=False)
print("Successfully created 'your_file.csv' in the Colab workspace!")

Successfully created 'your_file.csv' in the Colab workspace!

In [ ]:
# 1. Read the CSV file
try:
    df = pd.read_csv('your_file.csv')
    print("Original DataFrame Shape:", df.shape)
    print("\nFirst 5 rows:")
    print(df.head())
except FileNotFoundError:
    print("CSV file not found. Creating a sample DataFrame for demonstration...")
    data = {
        'Name': [' Alice ', 'Bob', 'Alice', 'Charlie', None],
        'Age': [25, 30, 25, None, 22],
        'Salary': ['50000', '60000', '50000', '70000', '45000']
    }
    df = pd.DataFrame(data)
    print("Sample DataFrame:")
    print(df)

# 2. Perform basic data cleaning methods

# Remove duplicate rows
df = df.drop_duplicates()

# Strip leading and trailing whitespaces from string columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

# Handle missing values
if 'Age' in df.columns:
    df['Age'] = df['Age'].fillna(df['Age'].median())

# Convert data types
if 'Salary' in df.columns:
    df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

print("\nCleaned DataFrame Shape:", df.shape)
print("\nCleaned DataFrame:")
print(df)

Index(['Name', 'Age', 'Salary'], dtype='object')

In [8]:
# 1. Read the fresh CSV file again
df_fixed = pd.read_csv('your_file.csv')

# 2. Strip whitespaces FIRST before dropping duplicates
# This ensures ' Alice ' and 'Alice' are recognized as the same value
for col in df_fixed.select_dtypes(include='object').columns:
    df_fixed[col] = df_fixed[col].astype(str).str.strip()

# 3. Handle the 'nan' string converted from NaN values
# We replace the literal string 'nan' back to a proper empty string or a placeholder like 'Unknown'
df_fixed['Name'] = df_fixed['Name'].replace('nan', 'Name not available')

# 4. Fill missing Age values
if 'Age' in df_fixed.columns:
    df_fixed['Age'] = df_fixed['Age'].fillna(df_fixed['Age'].median())

# 5. Convert Salary to numeric
if 'Salary' in df_fixed.columns:
    df_fixed['Salary'] = pd.to_numeric(df_fixed['Salary'], errors='coerce')

# 6. Now drop duplicates (after values have been normalized/cleaned!)
df_fixed = df_fixed.drop_duplicates()

# Display the correctly cleaned DataFrame
print("Correctly Cleaned DataFrame:")
display(df_fixed)

Correctly Cleaned DataFrame:

                 Name   Age  Salary
0               Alice  25.0   50000
1                 Bob  30.0   60000
3             Charlie  25.0   70000
4  Name not available  22.0   45000

In [13]:
# Method to apply some logic to each row and create new column.
def calculate_bonus(row):
    # Custom logic: if the age is over 25, they get a 10% bonus, otherwise 5%
    if row['Age'] > 25:
        return row['Salary'] * 0.10
    else:
        return row['Salary'] * 0.05

# Apply the function to each row (axis=1 refers to row-by-row operations)
df_fixed['Bonus'] = df_fixed.apply(calculate_bonus, axis=1)

# Display the updated DataFrame
display(df_fixed)

                 Name   Age  Salary   Bonus
0               Alice  25.0   50000  2500.0
1                 Bob  30.0   60000  6000.0
3             Charlie  25.0   70000  3500.0
4  Name not available  22.0   45000  2250.0

In [15]:
# pandas where clause
import numpy as np

# Example 1: Using numpy.where to create a conditional column
# If Salary is greater than 55000, label as 'High', otherwise 'Standard'
df_fixed['Salary_Class'] = np.where(df_fixed['Salary'] > 55000, 'High', 'Standard')

# Example 2: Using pandas DataFrame.where to replace values conditionally
# df.where replaces values where the condition is FALSE.
# Let's cap any salary above 65000 to exactly 65000
df_fixed['Capped_Salary'] = df_fixed['Salary'].where(df_fixed['Salary'] <= 65000, 65000)

display(df_fixed)

                 Name   Age  Salary   Bonus Salary_Class  Capped_Salary
0               Alice  25.0   50000  2500.0     Standard          50000
1                 Bob  30.0   60000  6000.0         High          60000
3             Charlie  25.0   70000  3500.0         High          65000
4  Name not available  22.0   45000  2250.0     Standard          45000

In [11]:
df_fixed.columns

Index(['Name', 'Age', 'Salary', 'Bonus'], dtype='object')

In [12]:
df_fixed.shape

(4, 4)